//
// Menu.swift
// Ez Menu Generator
//
// MARK: - Purpose
// Defines the 7-day menu structure containing:
// - Menu metadata (name, week start date)
// - 7 DayMeals (breakfast, lunch, dinner for each day)
// - Constraint tracking for dietary restrictions
//
// MARK: - Usage
// - Generated by MenuListViewModel.generateMenu()
// - Edited in MenuEditorView
// - Validated against constraints via ConstraintTracker
// - Shopping lists derived from menu recipes
//

import Foundation
import SwiftData

@Model
final class Menu {
    @Attribute(.unique) var id: UUID
    var name: String
    var weekStartDate: Date
    @Relationship(deleteRule: .cascade, inverse: \DayMeals.menu) var meals: [DayMeals] = []
    var lastModifiedAt: Date
    var notes: String?
    
    init(
        id: UUID = UUID(),
        name: String,
        weekStartDate: Date,
        meals: [DayMeals] = [],
        lastModifiedAt: Date = Date(),
        notes: String? = nil
    ) {
        self.id = id
        self.name = name
        self.weekStartDate = weekStartDate
        self.lastModifiedAt = lastModifiedAt
        self.notes = notes
        
        // Initialize with empty days if not provided
        if meals.isEmpty {
            self.meals = (0..<7).map { _ in DayMeals() }
        } else {
            // Ensure exactly 7 meals, pad if necessary
            var mealsList = meals
            while mealsList.count < 7 {
                mealsList.append(DayMeals())
            }
            self.meals = Array(mealsList.prefix(7))
        }
        
        // Set back-reference for all meals
        for dayMeal in self.meals {
            dayMeal.menu = self
        }
    }
}

@Model
final class DayMeals {
    var breakfast: Recipe?
    var lunch: Recipe?
    var dinner: Recipe?
    var menu: Menu?
    
    init(breakfast: Recipe? = nil, lunch: Recipe? = nil, dinner: Recipe? = nil) {
        self.breakfast = breakfast
        self.lunch = lunch
        self.dinner = dinner
        self.menu = nil
    }
}
